name: lomtter
description: Generador automático de modelos en Dart/Flutter inspirado en Lombok
version: 1.0.2
repository: https://github.com/tu_usuario/lomtter
homepage: https://github.com/tu_usuario/lomtter
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
